name: Stefan Wessel
favicon: null
layout_spectrum: 1
typography_spectrum: 0.57426
title: 'Singer, Bassplayer, AudioEngineer, Producer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0a0a'
    - '#ffffff'
    - '#141a4f'
    - '#1b4594'
    - '#2777be'
  brandStrength: 0.5
  lightness: 0.125
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
