name: Stefan Wessel
favicon: null
layout_spectrum: 0.13195264781825244
typography_spectrum: 0.01696844701655209
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.9652605215087533
  lightness: 0.56560053024441
  saturation: 0.9890906314831227
  rhythmicContrast: 0.4476910228841007
purpose: []
